create database QuanLyNhanVien
go

use QuanLyNhanVien
go

CREATE TABLE PHONGBAN (
	MAPB CHAR (5) NOT NULL PRIMARY KEY,
	TENPB NVARCHAR(50) NOT NULL
	)
GO

CREATE TABLE CHUCVU (
	MACV CHAR (5) NOT NULL PRIMARY KEY,
	TENCV NVARCHAR (50) NOT NULL
	)
GO

create table NHANVIEN(
	MANV CHAR (5) NOT NULL PRIMARY KEY,
	HOTEN NVARCHAR (50) NOT NULL,
	NGAYSINH DATETIME NOT NULL,
	GIOITINH BIT NOT NULL CHECK (GIOITINH IN(1,0)),
	DIACHI NVARCHAR(100) NOT NULL,
	MAPB CHAR (5) NOT NULL FOREIGN KEY (MAPB) REFERENCES PHONGBAN(MAPB),
	MACV CHAR (5) NOT NULL FOREIGN KEY (MACV) REFERENCES CHUCVU(MACV),
	LUONGCB FLOAT,
	HESOLUONG FLOAT
	)
GO

CREATE TABLE LUONG (
	MANV CHAR (5) NOT NULL,
	NGAY DATE NOT NULL,
	LUONGTHUONG FLOAT NOT NULL,
	PHUCAP FLOAT NOT NULL,
	PRIMARY KEY (MANV,NGAY),
	FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
	)
GO

INSERT INTO PHONGBAN VALUES ('PB01',N'Phòng Kế Toán');
INSERT INTO PHONGBAN VALUES ('PB02',N'Phòng Nhân Sự');
INSERT INTO PHONGBAN VALUES ('PB03',N'Phòng Kỹ Thuật');
go

INSERT INTO CHUCVU VALUES ('CV01',N'Nhân Viên');
INSERT INTO CHUCVU VALUES ('CV02',N'Trưởng Phòng');
INSERT INTO CHUCVU VALUES ('CV03',N'Giám Đốc');
go

INSERT INTO NHANVIEN VALUES ('NV01',N'Nguyễn Văn A','1985-01-01',1,N'Hà Nội','PB01','CV01',5000000,1.2);
INSERT INTO NHANVIEN VALUES ('NV02',N'Trần Thị B','1990-02-02',0,N'Hải Phòng','PB02','CV02',7000000,1.5);
INSERT INTO NHANVIEN VALUES ('NV03',N'Lê Văn C','1988-03-03',1,N'ĐÀ NẴng','PB03','CV03',9000000,2.0);
go

INSERT INTO LUONG VALUES ('NV01','2023-06-01',500000,200000);
INSERT INTO LUONG VALUES ('NV02','2023-06-01',700000,300000);
INSERT INTO LUONG VALUES ('NV03','2023-06-01',900000,400000);
GO

SELECT * FROM NHANVIEN
SELECT * FROM PHONGBAN
SELECT * FROM CHUCVU
SELECT * FROM LUONG
GO